datax = load('mperf_X_train.tsv');
X = datax(:,1);
Y = datax(:,2);
Z = datax(:,3);
datay = load('mperf_y_train.tsv');
figure;
ind = find(datay==1);
scatter3(X(ind),Y(ind),Z(ind),[],'b.');
hold on;
ind = find(datay==-1);
scatter3(X(ind),Y(ind),Z(ind),[],'r.');

datax = load('mperf_X_test.tsv');
X = datax(:,1);
Y = datax(:,2);
Z = datax(:,3);
datay = load('mperf_y_test.tsv');
ind = find(datay==1);
scatter3(X(ind),Y(ind),Z(ind),[],'g.');
hold on;
ind = find(datay==-1);
scatter3(X(ind),Y(ind),Z(ind),[],'y.');
